TravelApiClient/Controllers/ReviewsController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TravelApiClient.Models;

namespace TravelApiClient.Controllers
{
    public class ReviewsController : Controller
    {
        public async Task<ActionResult> Index(string country, string city, string option)
        {
            try
            {
                Payload cookieValueFromReq = Payload.GetPayloadObject(HttpContext);
                DateTime date = DateTime.Now;
                DateTime dateJWT = Payload.UnixTimestampToDateTime(cookieValueFromReq.exp);
                List<Review> reviews = await Review.GetReviews(country, city, option);
                ViewBag.expired = date > dateJWT;

                return View(reviews);
            }
            catch
            {
                List<Review> reviews = await Review.GetReviews(country, city, option);
                return View(reviews);
            }
        }

        public async Task<ActionResult> Popular(string option)
        {
            List<string> strings = await Review.Popular(option);
            return View(strings);
        }

        public async Task<ActionResult> Random()
        {
            string result = await Review.GetRandom();
            ViewBag.result = result;
            return View();
        }

        public async Task<ActionResult> Details(int id)
        {

            try
            {
                Payload cookieValueFromReq = Payload.GetPayloadObject(HttpContext);
                DateTime date = DateTime.Now;
                DateTime dateJWT = Payload.UnixTimestampToDateTime(cookieValueFromReq.exp);

                Review review = await Review.GetDetails(id);
                ViewBag.expired = date > dateJWT;
                ViewBag.userName = cookieValueFromReq.aud;
                return View(review);
            }
            catch
            {
                Review review = await Review.GetDetails(id);
                return View(review);
            }
        }

        public ActionResult Create()
        {
            try
            {
                Payload cookieValueFromReq = Payload.GetPayloadObject(HttpContext);
                DateTime date = DateTime.Now;
                DateTime dateJWT = Payload.UnixTimestampToDateTime(cookieValueFromReq.exp);
                ViewBag.expired = date > dateJWT;
                return View();
            }
            catch
            {
                return View();
            }

        }

        [HttpPost]
        public async Task<ActionResult> Create(Review review)
        {
            await Review.Post(review, HttpContext);
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Edit(int id)
        {
            try
            {
                Payload cookieValueFromReq = Payload.GetPayloadObject(HttpContext);
                DateTime date = DateTime.Now;
                DateTime dateJWT = Payload.UnixTimestampToDateTime(cookieValueFromReq.exp);

                Review review = await Review.GetDetails(id);
                ViewBag.expired = date > dateJWT;
                ViewBag.userName = cookieValueFromReq.aud;
                return View(review);
            }
            catch
            {
                Review review = await Review.GetDetails(id);
                return View(review);
            }
        }
        [HttpPost]
        public async Task<ActionResult> Edit(Review review)
        {
            await Review.Put(review, HttpContext);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<ActionResult> Delete(int id)
        {
            await Review.Delete(id, HttpContext);
            return RedirectToAction("Index");
        }
    }
}

TravelApiClient/Views/Reviews/Create.cshtml
@model TravelApiClient.Models.Review


@if (ViewBag.expired == true)
{
  <div>Your login session has expired. Login again to add a new review</div>
}
else if (ViewBag.expired == false)
{
  <div>
    @using (Html.BeginForm())
    {
      <div class="form-group">
        @Html.LabelFor(x=>x.Rating)
        @Html.DropDownList("Rating",
    Html.GetEnumSelectList<Rating>(),
    "Select Rating",new { @class = "form-control" , required = "required"})
      </div>
      <div class="form-group">
        @Html.LabelFor(x=>x.Country)
        @Html.TextBoxFor(x=>x.Country,new { @class = "form-control" , required = "required"})
      </div>
      <div class="form-group">
        @Html.LabelFor(x=>x.City)
        @Html.TextBoxFor(x=>x.City,new { @class = "form-control", required = "required" })
      </div>

      <input type="submit" value="Post" class="form-control">
    }
  </div>
}
else
{
  <div>You must login and/or register a new account to add reviews</div>
}

TravelApiClient/Views/Reviews/Details.cshtml
<div>
  <p>Id: @Model.ReviewId</p>
  <p>Rating: @Model.Rating</p>
  <p>UserName: @Model.UserName</p>
  <p>Country: @Model.Country</p>
  <p>City: @Model.City</p>
</div>

@if(@ViewBag.userName == @Model.UserName && @ViewBag.expired == false)
{
<div>
  @Html.ActionLink("Edit","Edit",new{id = @Model.ReviewId})
  @using (Html.BeginForm("Delete", "Reviews", new { id = @Model.ReviewId }))
  {
    <input type="submit" value="Delete" class="form-control">
  }
</div>
}

TravelApiClient/Views/Reviews/Edit.cshtml
@model TravelApiClient.Models.Review
@if (@ViewBag.userName == @Model.UserName && @ViewBag.expired == false)
{
  <div>
    @using (Html.BeginForm())
    {

      @Html.HiddenFor(x=>x.ReviewId)
      <div class="form-group">
        @Html.LabelFor(x=>x.Rating)
        @Html.DropDownList("Rating",
    Html.GetEnumSelectList<Rating>(),
    "Select Rating",new { @class = "form-control", required = "required" })
      </div>
      <div class="form-group">
        @Html.LabelFor(x=>x.Country)
        @Html.TextBoxFor(x=>x.Country,new { @class = "form-control", required = "required" })
      </div>
      <div class="form-group">
        @Html.LabelFor(x=>x.City)
        @Html.TextBoxFor(x=>x.City,new { @class = "form-control", required = "required" })
      </div>

          <input type="submit" value="Edit" class="form-control">
    }
  </div>
}
else
{
  <div>You must be logged in as @Model.UserName to edit this review</div>
}

TravelApiClient/Views/Reviews/Index.cshtml
@using TravelApiClient.Models
@if (ViewBag.expired == true)
{
  <div>Your login session has expired. Login again to add a new review</div>
}
else if (ViewBag.expired == false)
{
  <div>@Html.ActionLink("Add a new review","Create","Reviews")</div>
}
else
{
  <div>You must login and/or register a new account to add reviews</div>
}

<hr>
@using (@Html.BeginForm("Index", "Reviews", FormMethod.Get))
{
  <div class="form-group">
    @Html.Label("Country")
    @Html.TextBox("country",null,new { @class = "form-control" })
  </div>
  <div class="form-group">
    @Html.Label("City")
    @Html.TextBox("city",null,new { @class = "form-control" })
  </div>
  <div class="form-group">
    @Html.Label("Option")
    @Html.DropDownList("option",new List<SelectListItem>{new SelectListItem("Choose",""),new
  SelectListItem("Rating","rating"),new SelectListItem("Number","number")},new { @class = "form-control" })
  </div>
    <input type="submit" value="Search" class="form-control">
}
<hr>
@using (@Html.BeginForm("Popular", "Reviews", FormMethod.Get))
{
  <div class="form-group">
    @Html.Label("Option")
    @Html.DropDownList("option",new List<SelectListItem>{new SelectListItem("Rating","rating"),new
  SelectListItem("Number","number")},new { @class = "form-control" })
  </div>
  <input type="submit" value="See most popular" class="form-control">
}
<hr>
@Html.ActionLink("See a random destination","Random","Reviews");
<hr>
@foreach (Review review in @Model)
{
  <div>
    <p>@Html.ActionLink(@review.City + ", " + @review.Country,"Details",new{id = @review.ReviewId})</p>
  </div>
}

TravelApiClient/Views/Reviews/Popular.cshtml
@foreach (string s in @Model)
{
  <p>@s</p>
}

TravelApiClient/Views/Reviews/Random.cshtml
<p>@ViewBag.result</p>